apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: cicd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://kubernetes-charts.storage.googleapis.com'
    targetRevision: 4.0.1
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: persistence.size
          value: 2Gi
        - name: ingress.enabled
          value: 'true'
        - name: 'ingress.hosts[0].name'
          value: sonar.local.kube.azeops.com
        - name: 'ingress.tls[0].hosts[0]'
          value: sonar.local.kube.azeops.com
        - name: 'ingress.tls[0].secretName'
          value: cicd-sonar-tls
        - name: service.externalPort
          value: '443'
      values: |-
        ingress:
          enabled: true
          hosts:
            - name: sonar.local.kube.azeops.com
              path: /
              
          annotations:
              kubernetes.io/ingress.class: "nginx"
              certmanager.k8s.io/cluster-issuer: "selfsigning-issuer"
              certmanager.k8s.io/acme-challenge-type: http01
          
    chart: sonarqube
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: cicd
  syncPolicy: {}
